version: "3"

services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - grafana
      - monitor
    volumes:
      - grafana-volume:/var/lib/grafana
    deploy:
      placement:
        constraints: [node.role == manager]

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    networks:
      - grafana
    volumes:
      - influxdb-volume:/var/lib/influxdb
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  grafana:
  monitor:
    external: true
  
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true