version: '3.1'

services:

  master:
    image: vfarcic/jenkins:scale
    ports:
      - 8080:8080
    #environment:
    #  - JENKINS_OPTS="--prefix=/jenkins"
    dns:
      - 10.0.2.3
      - 8.8.8.8
    networks:
      - default
    deploy:
      placement:
        constraints: [node.role == manager]
      #labels:
        #- com.df.notify=true
        #- com.df.distribute=true
        #- com.df.servicePath=/jenkins
        #- com.df.port=8080
      resources:
        reservations:
          memory: 800M
        limits:
          memory: 1024M
    extra_hosts:
      - "${SLACK_HOST:-devops20.slack.com}:${SLACK_IP:-13.35.21.158}"
    secrets:
      - jenkins-user
      - jenkins-pass

  agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://master:8080 -labels 'prod' -executors 4
    dns:
      - 10.0.2.3
      - 8.8.8.8
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 150M
        limits:
          memory: 300M

networks:
  default:
    external: false

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
