version: '3.3'

services:
   main:
     image: heroahmadi/staticapp
     volumes:
     - /app/test/dataset
     networks:
      - proxy
      - monitor
     ports:
      - "5000"
     deploy:
      restart_policy:
        condition: any
      mode: replicated
      placement:
        constraints: [node.role == worker]
      update_config:
        # parallelism: 1
        delay: 2s
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=5000
        - com.df.scaleMin=2
        - com.df.scaleMax=7
        - com.df.alertName.1=mem_limit
        - com.df.alertIf.1=@service_mem_limit:0.9
        - com.df.alertFor.1=5m
        - traefik.docker.network=proxy
        - traefik.port=5000
        - traefik.frontend.rule=PathPrefix:/;
        # - traefik.backend.loadbalancer.sticky=true
      resources:
        reservations:
          cpus: '0.05'
          memory: 64M
        limits:
          cpus: '0.125'
          memory: 128M

networks:
  proxy:
    external: true
  monitor:
    external: true