version: '3'

services:

  main:
    image: heroahmadi/testserver
    networks:
      - proxy
      - monitor
    environment:
      - PREFIX=/app
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/app
        - com.df.port=5000
        - com.df.scaleMin=2
        - com.df.scaleMax=4
        - com.df.alertName.1=mem_limit
        - com.df.alertIf.1=@service_mem_limit:0.8
        - com.df.alertFor.1=5m
      resources:
        reservations:
          memory: 15M
        limits:
          memory: 30M

networks:
  proxy:
    external: true
  monitor:
    external: true